#!/usr/bin/env ruby

$-w = true

unless STDOUT.isatty
  # Reopen io to somewhere we can see it.
  STDOUT.reopen(Dir.getwd + "/vpimd.log", "w")
  STDERR.reopen(STDOUT)
end

STDOUT.sync = STDERR.sync = true

puts "daemon base: #{Dir.getwd}"

require "vpim/agent/main"

