messages=yes
debug=yes

include $(GNUSTEP_MAKEFILES)/common.make

TOOL_NAME=contacts
contacts_OBJC_FILES=contacts.m FormatHelper.m
contacts_LDFLAGS += -lMyFolks
contacts_OBJCFLAGS += -Wno-import -Dtrue=YES -Dfalse=NO

-include GNUmakefile.preamble
-include GNUmakefile.local
include $(GNUSTEP_MAKEFILES)/tool.make
-include GNUmakefile.postamble

after-contacts-install::
	mkdirhier $(GNUSTEP_DOCUMENTATION_MAN)/man1 && \
	 cp contacts.1 $(GNUSTEP_DOCUMENTATION_MAN)/man1


